RANDOM_SEED : 2021                        # 随机数种子

EPISODE_START_SAVE : 400                  # episode > EPISODE_START_SAVE, 则开始eval并保存模型

NUM_DRONE : 2                             # 无人机数量

N_STEP_RETURN : 3

# task设置
# FINISH_PERCENTAGE : 0.1                   # 信号点剩余总数据量低于DATA_TOTAL * FINISH_PERCENTAGE时，感知任务完成

# 动作设置
DIMENSION_ACTION : [2, 2]                   # 动作值维度
DIMENSION_OBS : [180, 40]
# DIMENSION_OBS : [624, 40]                   # 全局dim

# drone初始参数
DEPARTURE_POS :  [-2, -2, 2]                # 起点坐标[[2, -5, 2], [4, 3, 2], [-4, -1, 2]] 
# DEPARTURE_POS : [0,0,3.3]                 # 起点坐标[[2, -5, 2], [4, 3, 2], [-4, -1, 2]] [[0.7, 0, 2], [-0.35, 0.606, 2], [-0.7, -0.606, 2]]
DIRECTION_INITIAL : [0., 0., 1.5707963]   # 角度

# goal
# GOAL_DISTANCE_THRESHOLD : 0.15
# HEIGHT_SAFETY : 3

# reward函数
REWARD_CLOSE_TO_MOST_ATTRACTIVE_SP : 0.05
PENALTY_DILEMMA : 2
PENALTY_STEP_THRESHOLD : 0.8
STEP_THRESHOLD : 600
PENALTY_INSPIRE : 0.03
REWARD_INSPIRE_FLY_OVER : 0.01
REWARD_INSPIRE : 0.02                     # 用于激励探索的奖励，避免原地打转
REWARD_SENSING_ENERGY_CONSUMPTION : 0.1   # 单位感知能量消耗奖励
PENALTY_MOVING_ENERGY_CONSUMPTION : 0.1   # 单位移动能力消耗惩罚
POTENTIAL_SENSING_EXTENT_DIVISION : 4     # INTERNAL_WIDTH / 2**0, INTERNAL_WIDTH / 2**1, INTERNAL_WIDTH / 2**2, INTERNAL_WIDTH / 2**3
POTENTIAL_SENSING_EXTENT : 2.4            # 未来潜在感知信号点的范围
REWARD_POTENTIAL_SENSING : 0.02           # 未来潜在感知信号点数量增加 / 距离减少的奖励
REWARD_SENSED : 0.5                       # 收集数据奖励常数，0.1 * 感知范围内信号点数量m * （数据收集量 / （m*感知能力））
PENALTY_NO_SENSED : 1                     # 未收集数据惩罚
DATA_SENED_THRESHOLD : 0.95               # 收集数据比例阈值，大于该阈值则完成任务
REWARD_SENSING_TASK_COMPLETED : 100       # 收集完成奖励
PENALTY_COLLISON : 100                    # 碰撞惩罚（除充电以外的与任何物体接触：包括但不限于障碍物、其他无人机、坠机、越过限定高度）
DISTANCE_LASER_TOO_CLOSE : 0.3            # 激光长度低于DISTANCE_LASER_TOO_CLOSE时，增加惩罚PENALTY_TOO_CLOSE
PENALTY_TOO_CLOSE : 2                     # 激光长度低于DISTANCE_LASER_TOO_CLOSE时的惩罚
REWARD_NOT_TOO_CLOSE : 0.1                 # 激光长度大于DISTANCE_LASER_TOO_CLOSE时的奖励
PENALTY_CONSTANT : 0.01
PENALTY_INTER_POI : 0.2

REWARD_MOVEMENT : 0.25                    # 移动探索奖励
PENALTY_NO_MOVEMENT : 0.5                 # 无移动探索惩罚
NUM_REWARD_CLOSE_SP : 2                   # 感知范围内信号点数量奖励阈值
REWARD_CLOSE_SP : 0.2                     # 感知范围内信号点数量达到阈值的奖励
PENALTY_CLOSE_SP : 0.5                    # 感知范围内信号点数量未达到阈值的惩罚
REWARD_NUM_ADD_CLOSE_SP : 0.5             # 感知范围内信号点数量增加的奖励

# scene
CENTER_POS : [0., 0., 0.]                 # 围墙中心坐标
INTERNAL_LENGTH : 16                      # 围墙的内矩形长
INTERNAL_WIDTH : 16                       # 围墙的内矩形宽
HEIGHT : 10                               # 围墙高度
THICKNESS : 2                             # 围墙厚度
FENCE_MASS : 100000.                      # 围墙重量
FENCE_COLOR : [1., 1., 1., 1.]            # 围墙颜色

NUM_OBSTACLE : 6                          # 障碍物数量

NUM_SIGNAL_POINT : 100                    # 信号点数量
NUM_MAX_SENSED_SIGNAL_POINT : 26 
# NUM_MAX_SENSED_SIGNAL_POINT : 100           #最多能感知到的信号点数量，原26
# DATA_TOTAL : 2000                        # 信号点数据总量
SIGNAL_POINT_RADIUS : 0.1                 # 信号点半径
SIGNAL_POINT_COLOR : [0., 0., 1., 1.]     # 信号点颜色

USE_MAX_COOR : False                      # 是否使用最大化坐标刻度

# drone 参数
DRONE_SCALE : 0.2                        # 无人机大小
DRONE_COLOR : [1., 0., 0., 1.]            # 无人机颜色
DRONE_WEIGHT : 12.                        # 无人机重量
DRONE_FORCE : 90000. #80000.               # 推力
SENSING_EXTENT : 1.2                      # 感知范围
DATA_PER_ROUND : 0.2                      # 每次收集的数据量

# drone能量消耗函数
MAX_DATA_COLLECTED_PER_STEP : 0.6         # 单步最大数据收集量（用于归一化）(DATA_PER_ROUND * 3)
MAX_DISTANCE_MOVEMENT_PER_STEP : 0.13     # 单步最大运动距离（用于归一化）
UNIT_DATA_COLLECTED_PER_STEP : 0.2        # 单步单元数据收集量
SENSE_COMSUMPTION : 0.1                   # 感知单位数据量所消耗电量[0.1, 0.2, 0.3]
MOVE_COMSUMPTION : 1                      # 移动单位距离所消耗电量
MAX_ENERGY_CONCUMPTION_PER_STEP : 1.3     # 单步最大能量消耗量[1.3, 1.6, 1.9]

# 充电
NUM_CHARGER : 1
DEPARTURE_POS_CHARGER : [[0, -5, 1], [1, 5, 1]] #0 -5
CHARGE_RANGE : 1.5
ENERGY_PERSTEP : 0.004
ENERGY_PERSENSE : 0.007
CHARGE : 0.03                             # 充电量
MAX_CHARGE : 1                         # 最大充电量
CHARGER_COLOR : [0., 1., 0., 1.]          # 充电桩颜色
ENERGY_SHREHOLD : 0.05
REWARD_CHARGE : 1.6
DIS_TO_CLOSEST_UAV: -0.2
ENERGY_TO_CLOSEST_UAV : -0.08
PENALTY_NOT_CHARGE : 100
WEI : 0.5

# 激光参数
# LASER_LENGTH : 4.                         # 激光长度
LASER_LENGTH : 16.                         # 全局激光长度
LASER_NUM_HORIZONTAL : 24                 # 水平激光数量
LASER_NUM_VERTICAL : 10                   # 竖直激光数量

# 外部观测值设置
CLOSEST_SIGNAL_NUM : 6                    # 获取距离最近的CLOSEST_SIGNAL_NUM个信号点的信息（数据剩余量、距离、位置、方向）
CLOSEST_CHARGER_NUM : 3                   # 最多获取距离最近的CLOSEST_CHARGER_NUM个充电桩的信息（距离、位置、方向及是否有其他无人机在充电）
DIMENSION_OBSERVATION_SP : 2              # 每个信号点的观测值的维度
DIMENSION_OBSERVATION_CHARGER : 2         # 每个充电桩的观测值的维度
DIMENSION_OBSERVATION_RAYS : 1            # 每条激光的观测值的维度

# debug 参数
DEBUG_TEXT_COLOR : [0., 0., 0.]           # debug文本的颜色
DEBUG_TEXT_SIZE : 1.2                     # debug文本的大小
MISS_COLOR : [0., 1., 0.]                 # 没有命中的激光的颜色
HIT_COLOR : [1., 0., 0.]                  # 命中的激光的颜色
RAY_DEBUG_LINE_WIDTH : 2.                 # 激光的debug线的宽度

# 其他参数
USE_MAX_COOR : False                      # 是否使用最大化坐标刻度
